apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: "https://103.185.52.45:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpFek9UQTRNRFF3SGhjTk1qWXdNakU0TURVd01EQTBXaGNOTXpZd01qRTJNRFV3TURBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpFek9UQTRNRFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTckpZTUNCdG9kU2lGZ2k1bkJ0YnNRaE4wcTRnSmRJQ2lzeGRwN2FGR00KcTVaWk5iQXpLbjNrd05hU2JmZ2sxL2xUQWFIWnFSUlI0czdqaEFIclhUMjZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXdHdVk4YVZ2QzVURDZnaUdFQlNTCmRrK2loU2t3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnYld1Y1NkQUVsZ3orcmp2Z1hrU0hXTTRSQnlrQVo4VjQKWDBlTjhYZzdJMmNDSVFDZWRtR2pVMzVQaUtheVFnQS9NWHJMd2ZyL1pBeUU3eUJzWHo2bGN5VFZKZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
contexts:
- name: weci-holic
  context:
    cluster: local
    namespace: weci-holic
    user: weci-holic-sa
current-context: weci-holic
users:
- name: weci-holic-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlFteFl2cGk1RkF5TEFkdDJYSC05UnVmUGJhYXJCU0pBNjNEcUZxcEtsdFUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ3ZWNpLWhvbGljIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6IndlY2ktaG9saWMtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoid2VjaS1ob2xpYy1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjhlNjY0ZmQyLWNkNTYtNGEyNi1iNjE5LWRjYzg1Y2Y2ZWFjMiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp3ZWNpLWhvbGljOndlY2ktaG9saWMtc2EifQ.jlBrE-ajb4CCj2244Kl-B-5jXikmNOh1kwbnMKttZFE8OJSi9xUEc1x6oQni1P83p5pkbqvreZpN8FtA-_YiMJpyMkjInWogfBc7TVvymJ0F0KQ-Ybxu2ibxkQvOOlNLuctCq4NbCm0oQaH3iBlvsFMpKuZJnogDwEbc6fompYrsxdXGh4F-zoh91mGiSsc7vyLfNJrKQvkivoOoaVwP2Y9xIZUnXMiTCExLUo1DthbRVN4PMPiCytJ6Tvg4LSMruu9-nW2be1hCgTV5IffB4hlhIgaWwCpBzygiWM4--Yg0tS-lejbquehDhVTWMkeOoZqzRKnMdU5iVyxBGB0pOA
