apiVersion: v1
kind: Secret
metadata:
  name: legac-secret
  namespace: weci-holic
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3dlY2lfaG9saWM6Zj09K0hMSF9idnpMTjJmbzgyZjN4MjM5TVpFMyU0MGJHRkAxMDMuMTg1LjUyLjEzODoxMTg1L3dlY2lfaG9saWM=
  GITHUB_ID: T3YyM2xpNHRCN3AzR2l6STdLdnk=
  GITHUB_SECRET: MzI1ZjE5Mjg5OGViM2I3ZGFiMGI5ZjU1MDdiODhmMzIyOTY4OWZjMA==
  AUTH_SECRET: TlRobE1qTmtOVGN0WW1FMVl5MDBNall5TFRnNVlXTXROMkprWTJNNU1EY3lNREEyTmpaalpUSmhZbU10WldVeU5DMDBOR0V6TFRrMll6Z3RNR1k0TnpRMk4yTmxZMlkx
  NEXTAUTH_URL: aHR0cHM6Ly93ZWNpLWhvbGljLmhhY2thdGhvbi5zZXYtMi5jb20=
