apiVersion: v1
kind: Secret
metadata:
  name: legac-secret
  namespace: weci-holic
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3dlY2lfaG9saWM6Zj09K0hMSF9idnpMTjJmbzgyZjN4MjM5TVpFMyU0MGJHRkAxMDMuMTg1LjUyLjEzODoxMTg1L3dlY2lfaG9saWM=
  GITHUB_ID: T3YyM2xpaWcxUW1ZRWJyMEFFU3U=
  GITHUB_SECRET: NDI2YTU5NDEwOWE1Y2Q1N2EyMGRkYTBiMTZkZjFhM2M2NTk4MjY1MQ==
  AUTH_SECRET: TlRobE1qTmtOVGN0WW1FMVl5MDBNall5TFRnNVlXTXROMkprWTJNNU1EY3lNREEyTmpaalpUSmhZbU10WldVeU5DMDBOR0V6TFRrMll6Z3RNR1k0TnpRMk4yTmxZMlkx
  NEXTAUTH_URL: aHR0cHM6Ly93ZWNpLWhvbGljLmhhY2thdGhvbi5zZXYtMi5jb20=
  AUTH_TRUST_HOST: dHJ1ZQ==
